// Generate the Archive "Explore by Theme" data: lib/archiveThemes.js.
// Themes are a small, approved editorial set; each debate is assigned to ALL
// themes it is semantically close to (multi-label) by comparing its stored
// Gemini embedding to a theme-description embedding, in the mean-centered space
// (raw Gemini cosines are uniformly high; centering makes them discriminate).
// Deterministic + data-driven. Run: node scripts/generate-themes.mjs [--write]
import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os';
import { embedText } from '../lib/related.mjs';
function loadEnv(p){ if(!fs.existsSync(p))return; for(const line of fs.readFileSync(p,'utf8').split('\n')){const t=line.trim();if(t&&!t.startsWith('#')&&t.includes('=')){const[k,...r]=t.split('=');if(!(k.trim() in process.env))process.env[k.trim()]=r.join('=').trim().replace(/^['"]|['"]$/g,'');}} }
loadEnv(path.join(process.cwd(),'.env.local')); loadEnv(path.join(os.homedir(),'.claude','secrets','gemini.env'));
const SB=process.env.NEXT_PUBLIC_SUPABASE_URL, KEY=process.env.SUPABASE_SERVICE_ROLE_KEY, GK=process.env.GEMINI_API_KEY;
const WRITE=process.argv.includes('--write');
const THRESH=parseFloat(process.env.THEME_THRESH||'0.20'); // min centered cosine to join a theme
const MAX_THEMES=3; // a debate joins at most its 3 strongest themes (above THRESH)

// Approved themes (order = display order) + a short description used only to
// compute the theme's semantic anchor. Membership is decided by the debates.
const THEMES=[
  ['Democracy','Democratic legitimacy and renewal: political polarization, public trust in institutions, electoral and parliamentary systems, governance and bureaucratic reform, the resilience of liberal democracy.'],
  ['Strategic Autonomy','Strategic autonomy and self-reliance: reducing dependence on other powers, European defense and a sovereign military, trade barriers and economic decoupling, building sovereign technological and industrial capability.'],
  ['War & Peace','War and peace: armed conflict and military intervention, deterrence, economic sanctions, peace negotiations and ceasefires, security threats between states.'],
  ['World Order','The global balance of power: US versus China rivalry, hegemony and the future of the American-led world order, the rise and fall of great powers.'],
  ['Inequality','Economic inequality and redistribution: wealth distribution, taxation and wealth taxes, the welfare state, poverty, and who benefits from growth and automation.'],
  ['AI & Technology','Artificial intelligence and technology: AI governance and regulation, digital infrastructure and data, automation, and the social and economic impact of new technology.'],
];

const norm=v=>{let s=0;for(const x of v)s+=x*x;const k=Math.sqrt(s)||1;return v.map(x=>x/k);};
const dot=(a,b)=>{let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s;};

const r=await fetch(`${SB}/rest/v1/sessions?select=slug,sharpened_issue,original_issue,cards,embedding&embedding=not.is.null&limit=5000`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}});
const rows=(await r.json()).filter(s=>Array.isArray(s.embedding)&&s.embedding.length);
const title=s=>((s.cards&&s.cards.question_en)||s.sharpened_issue||s.original_issue||'').trim();
const dim=rows[0].embedding.length;
const D=rows.map(s=>norm(s.embedding));
const mean=new Array(dim).fill(0); for(const v of D)for(let i=0;i<dim;i++)mean[i]+=v[i]/D.length;
const Dc=D.map(v=>norm(v.map((x,i)=>x-mean[i])));

console.error('[themes] embedding 6 theme descriptions via Gemini…');
const seeds=[]; for(const [,desc] of THEMES){ const e=norm(await embedText(desc,GK)); seeds.push(norm(e.map((x,i)=>x-mean[i]))); }

const sessionThemes={}; const counts=Object.fromEntries(THEMES.map(([l])=>[l,0]));
let unthemed=0;
rows.forEach((s,i)=>{
  const sims=THEMES.map(([l],j)=>({l,sim:dot(Dc[i],seeds[j])})).filter(x=>x.sim>=THRESH).sort((a,b)=>b.sim-a.sim).slice(0,MAX_THEMES);
  const labels=sims.map(x=>x.l);
  if(labels.length){ sessionThemes[s.slug]=labels; labels.forEach(l=>counts[l]++); } else unthemed++;
});

console.log('\n=== theme counts (threshold '+THRESH+', max '+MAX_THEMES+'/debate) ===');
for(const [l] of THEMES) console.log('  '+counts[l].toString().padStart(3)+'  '+l);
console.log('  '+unthemed.toString().padStart(3)+'  (untheméd → Full Archive only)');
const multi=Object.values(sessionThemes).filter(a=>a.length>1).length;
console.log('  debates in >1 theme: '+multi+' / '+rows.length);

// sample: show 6 debates with their assigned themes
console.log('\n=== sample assignments ===');
rows.slice(0,10).forEach(s=>console.log('  ['+(sessionThemes[s.slug]||['—']).join(', ')+']  '+title(s).slice(0,60)));

if(WRITE){
  const order=THEMES.map(([l])=>l);
  const out=`// AUTO-GENERATED by scripts/generate-themes.mjs — do not edit by hand.\n// Re-run after adding debates: node scripts/generate-themes.mjs --write\n\nexport const ARCHIVE_THEMES = ${JSON.stringify(order)};\n\nexport const SESSION_THEMES = ${JSON.stringify(sessionThemes,null,0)};\n`;
  fs.writeFileSync(path.join(process.cwd(),'lib','archiveThemes.js'),out);
  console.error('\n[themes] geschreven naar lib/archiveThemes.js');
}else{
  console.error('\n[dry-run] draai met --write om lib/archiveThemes.js te genereren.');
}
